spring.application.name=vault-transit-demo
spring.main.web-application-type=none
spring.main.keep-alive=true
debug=false

spring.cloud.vault.uri=${VAULT_ADDR}
spring.cloud.vault.authentication=CERT
spring.cloud.vault.ssl.cert-auth-path=cert
spring.cloud.vault.kv.enabled=false
spring.cloud.vault.config.lifecycle.enabled=false
spring.cloud.vault.session.lifecycle.enabled=true
spring.cloud.vault.session.lifecycle.refresh-before-expiry=10s
spring.cloud.vault.session.lifecycle.expiry-threshold=15s
spring.config.import=optional:vault://

spring.cloud.vault.ssl.key-store=${VAULT_KEYSTORE:file:/tmp/client.p12}
spring.cloud.vault.ssl.key-store-password=changeit
spring.cloud.vault.ssl.key-store-type=PKCS12
spring.cloud.vault.ssl.trust-store=${VAULT_TRUSTSTORE:file:/tmp/truststore.jks}
spring.cloud.vault.ssl.trust-store-password=changeit
spring.cloud.vault.ssl.trust-store-type=JKS

transit.path=transit
transit.key=kms
transit.interval-ms=${LOOP_INTERVAL_MS:20000}

logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.springframework.vault.authentication=INFO
logging.level.com.hashicorp=INFO
